### ISSUE TITLE
Deploy command for triggering jenkins jobs

### ISSUE THREAD

**Issue by dylanjustice** [AndcultureCode/AndcultureCode.Cli#127] opened 2020-10-29 13:09 UTC
For jenkins jobs that accept parameters, allow a command to trigger a jenkins job remotely.
Allow cli users to authenticate with a username, api token and server url, and persist that in a configuration.
Allow for creation of aliases for job names to make triggering easy, persist these to a configuration.
For the deploy command, require a tag name to be specified.
Finally, require a confirmation before deployment.

**Comment by brandongregoryscott** [comment] 2020-10-29 23:20
Duplicate of #128

**Closed by brandongregoryscott** 2020-10-29 23:20 UTC
